# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [9]:
standardized_X_test[0:10,]

array([[ 0.60929259, -0.8632695 ,  1.27212168,  1.48048047],
       [ 0.11527157, -1.07382303,  0.83914672,  0.45778014],
       [-0.54342312,  0.40005172, -0.83089958, -0.56492018],
       [ 0.77396626, -0.23160889,  1.27212168,  1.33438042],
       [ 0.60929259, -1.07382303,  0.59173245,  0.45778014],
       [-0.54342312,  1.4528194 , -0.95460671, -0.85712027],
       [-0.87277046, -0.23160889, -1.01646028, -1.00322032],
       [-1.69613883, -0.44216243, -1.01646028, -1.00322032],
       [-0.37874945,  2.08448001, -0.95460671, -1.14932036],
       [-1.36679148,  0.18949818, -1.01646028, -1.00322032]])

In [10]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [11]:
y_pred = perceptron.predict(standardized_X_test)

In [12]:
print(y_test)

[2 1 0 2 1 0 0 0 0 0 2 1 0 2 2 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1]


In [13]:
print(y_pred)

[2 1 0 2 1 0 0 0 0 0 2 2 0 2 2 0 1 2 2 0 0 0 2 2 0 0 0 2 0 1]


In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.40      0.57        10
           2       0.45      1.00      0.62         5

    accuracy                           0.80        30
   macro avg       0.82      0.80      0.73        30
weighted avg       0.91      0.80      0.79        30

